import "dotenv/config";

const { PORT,  MONGOSTRING, CLIENT_APP_URL, TELEGRAM_BOT_TOKEN, JWT_SECRET_KEY, JWT_SECRET_REFRESH_KEY } = process.env;

export const ENVVARIABLES = {
  PORT,
  MONGOSTRING,
  CLIENT_APP_URL,
  TELEGRAM_BOT_TOKEN,
  JWT_SECRET_KEY,
  JWT_SECRET_REFRESH_KEY
};
